Add support for OIDC token auth with AWS STS role
bakdata/kafka-large-message-serde pull request #21
Opened 2021-11-10 15:20 UTC by jclarysse

**Which problem this PR is trying to solve**
I am using the Serde with Kafka Connect, AWS S3 and STS [AssumeRole](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html). It works properly, however I now have the requirement to move to [AssumeRoleWithWebIdentity](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithWebIdentity.html).

**What is the suggested solution**
Extend AbstractLargeMessageConfig with new configuration parameter S3_JWT_PATH_CONFIG and provider of kind WebIdentityTokenCredentialsProvider.

**Additional information**
Related [issue](https://github.com/bakdata/kafka-large-message-serde/issues/20) was raised on main project.

2021-11-10 15:35 UTC, philipp94831 requested changes

2021-11-10 15:35 UTC, philipp94831 commented on large-message-core/src/main/java/com/bakdata/kafka/AbstractLargeMessageConfig.java
> +                            .roleArn(S3_ROLE_ARN_CONFIG)
this should be `roleArn` probably

2021-11-10 15:35 UTC, philipp94831 commented on large-message-core/src/main/java/com/bakdata/kafka/AbstractLargeMessageConfig.java
> +                            .roleSessionName(S3_ROLE_SESSION_NAME_CONFIG)
this should be `roleSessionName` probably

2021-11-10 15:35 UTC, philipp94831 commented on large-message-core/src/main/java/com/bakdata/kafka/AbstractLargeMessageConfig.java
> +                            .webIdentityTokenFile(S3_JWT_PATH_CONFIG)
this should be `jwtPath` probably

2021-11-10 15:35 UTC, philipp94831 commented on large-message-core/src/main/java/com/bakdata/kafka/AbstractLargeMessageConfig.java
> +            final AWSCredentialsProvider provider = !isEmpty(jwtPath)?
Please remove the check for empty `roleExternalId` from the outer if and create two ifs inside where you once check for empty `roleExternalId` and once for `jwtPath`

2021-11-10 15:35 UTC, philipp94831 commented on README.md
> +   Path to an OIDC token file in JSON format (JWT) used to authenticate before AWS STS role authorisation, ex. for EKS `/var/run/secrets/eks.amazonaws.com/serviceaccount/token`.
"ex." should be `e.g.,`

2021-11-10 15:35 UTC, philipp94831 commented on large-message-core/src/main/java/com/bakdata/kafka/AbstractLargeMessageConfig.java
> +    public static final String S3_JWT_PATH_CONFIG_DOC = "Path to an OIDC token file in JSON format (JWT) used to authenticate before AWS STS role authorisation, ex. for EKS `/var/run/secrets/eks.amaz
"ex." should be `e.g.,`

2021-11-10 15:35 UTC, philipp94831 commented on large-message-core/src/main/java/com/bakdata/kafka/AbstractLargeMessageConfig.java
> +    public static final String S3_JWT_PATH_CONFIG = S3_PREFIX + "jwt.path";
Please also update the JavaDoc of the class

2021-11-10 15:35 UTC, philipp94831 commented
Thanks for your contribution!

2021-11-12 12:50 UTC, philipp94831 requested changes
Your code is not compiling https://dev.azure.com/bakdata/public/_build/results?buildId=19261&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=2565f3a0-8e86-57ea-49fc-e0f2f63505c8&l=390

2021-11-12 17:24 UTC, philipp94831 requested changes

2021-11-12 17:24 UTC, philipp94831 commented on large-message-core/src/main/java/com/bakdata/kafka/AbstractLargeMessageConfig.java
> +            AWSCredentialsProvider provider = null;
This will not work because the optional constructor does not accept null. You can just immediately return inside the ifs as it was before

2021-11-12 17:24 UTC, jclarysse commented
Apologize, i didn't know how to setup a dev environment for Kotlin but finally got it to compile.

2021-11-15 14:18 UTC, philipp94831 approved these changes

2021-11-15 14:18 UTC, merged

2021-11-15 14:31 UTC, philipp94831 commented
@jclarysse I merged your PR. There is now a new Snapshot version `2.0.2-SNAPSHOT` in the Sonatype snapshot repo (https://oss.sonatype.org/content/repositories/snapshots). Can you please check if everything works as expected for you? Then I would make a release next

2021-11-16 17:53 UTC, jclarysse commented
@philipp94831 thank you very much! Will test soon and let you know if it works as expected.

2021-12-01 14:15 UTC, jclarysse commented
This message to confirm that in the meantime we tested that the change worked as expected.

2021-12-01 14:51 UTC, philipp94831 commented
> This message to confirm that in the meantime we tested that the change worked as expected.

Great to hear! I just released 2.1.0 which should be available in Maven Central shortly